<?php

namespace App\Models;

use App\Events\MessageSentEvent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    use HasFactory;

    protected $fillable = [
        'sender_id',
        'received_id',
        'content'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($message){
            $received = $message->recevied;
            broadcast(new MessageSentEvent($message->content,['id'=>$received->id,'name'=>$received->name,'profile_picture'=>$received->profile_picture]));
        });
    }


    public function sender()
    {
        return $this->belongsTo(User::class, 'sender_id', 'id');
    }

    public function recevied()
    {
        return $this->belongsTo(User::class, 'received_id', 'id');
    }

}
