<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'profile_picture',
        'account_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'account_id'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($user) {
            $account = Account::create([
                'account_number'=>Str::random(16),
                'balance' => 0
            ]);
            $user->account_id = $account->id;
        });
    }

    public function instructor()
    {
        return $this->hasOne(Instructor::class);
    }


    public function courses()
    {
        return $this->belongsToMany(Course::class)->using(CourseUser::class)->withTimestamps();
    }

    public function coursesForInstructor()
    {
        return $this->hasMany(Course::class, 'instructor_id', "id");
    }


    public function rates()
    {
        return $this->hasMany(Rate::class);
    }

    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    public function InstructorCourse()
    {
        return $this->hasOneThrough(Course::class, Instructor::class);
    }


    public function questions(): BelongsToMany
    {
        return $this->belongsToMany(Question::class, 'user_answers')
            ->withPivot('answer', 'mark', 'id')
            ->withTimestamps();
    }

    public function favoriteCourses()
    {
        return $this->belongsToMany(Course::class, 'user_favorites')->withTimestamps();
    }

    public function progress()
    {
        return $this->hasMany(StudentProgress::class);
    }

}

